//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Xml.Linq;
using System.Threading.Tasks;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using System;

namespace iReverse_Unisoc_Ultimate
{
	namespace Properties
	{

		//This class was auto-generated by the StronglyTypedResourceBuilder
		//class via a tool like ResGen or Visual Studio.
		//To add or remove a member, edit your .ResX file then rerun ResGen
		//with the /str option, or rebuild your VS project.
		///<summary>
		///  A strongly-typed resource class, for looking up localized strings, etc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"), global::System.Diagnostics.DebuggerNonUserCodeAttribute(), global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		internal static class Resources
		{

			private static global::System.Resources.ResourceManager resourceMan;

			private static global::System.Globalization.CultureInfo resourceCulture;

			///<summary>
			///  Returns the cached ResourceManager instance used by this class.
			///</summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Resources.ResourceManager ResourceManager
			{
				get
				{
					if (object.ReferenceEquals(resourceMan, null))
					{
						global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iReverse_Unisoc_Ultimate.Properties.Resources", typeof(Resources).Assembly);
						resourceMan = temp;
					}
					return resourceMan;
				}
			}

			///<summary>
			///  Overrides the current thread's CurrentUICulture property for all
			///  resource lookups using this strongly typed resource class.
			///</summary>
			[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static global::System.Globalization.CultureInfo Culture
			{
				get
				{
					return resourceCulture;
				}
				set
				{
					resourceCulture = value;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap _error
			{
				get
				{
					object obj = ResourceManager.GetObject("_error", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] C4
			{
				get
				{
					object obj = ResourceManager.GetObject("C4", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] Channel9
			{
				get
				{
					object obj = ResourceManager.GetObject("Channel9", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] exploit_4ee8
			{
				get
				{
					object obj = ResourceManager.GetObject("exploit_4ee8", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] exploit_65015f08
			{
				get
				{
					object obj = ResourceManager.GetObject("exploit_65015f08", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] exploit_65015f48
			{
				get
				{
					object obj = ResourceManager.GetObject("exploit_65015f48", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap icons8_cancel_25px
			{
				get
				{
					object obj = ResourceManager.GetObject("icons8_cancel_25px", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap info
			{
				get
				{
					object obj = ResourceManager.GetObject("info", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap logoireverse
			{
				get
				{
					object obj = ResourceManager.GetObject("logoireverse", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] msvcp140d
			{
				get
				{
					object obj = ResourceManager.GetObject("msvcp140d", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] sleep
			{
				get
				{
					object obj = ResourceManager.GetObject("sleep", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap success
			{
				get
				{
					object obj = ResourceManager.GetObject("success", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] ucrtbased
			{
				get
				{
					object obj = ResourceManager.GetObject("ucrtbased", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Byte[].
			///</summary>
			internal static byte[] vcruntime140d
			{
				get
				{
					object obj = ResourceManager.GetObject("vcruntime140d", resourceCulture);
					return (byte[])obj;
				}
			}

			///<summary>
			///  Looks up a localized resource of type System.Drawing.Bitmap.
			///</summary>
			internal static System.Drawing.Bitmap warning
			{
				get
				{
					object obj = ResourceManager.GetObject("warning", resourceCulture);
					return (System.Drawing.Bitmap)obj;
				}
			}
		}
	}

}